# Generated by Django 3.2.4 on 2021-06-15 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enderecos', '0002_alter_enderecos_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='enderecos',
            name='cep',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
