# Generated by Django 3.1.2 on 2021-04-21 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancelados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancelados',
            name='autor',
            field=models.CharField(blank=True, max_length=1),
        ),
    ]
