# Generated by Django 3.1.2 on 2020-10-29 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ofertas',
            name='qntdhoras',
        ),
        migrations.AddField(
            model_name='ofertas',
            name='time_final',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
