# Generated by Django 3.1.2 on 2021-03-13 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0003_ofertas_edit'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertas',
            name='canceled',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
