# Generated by Django 3.1.2 on 2021-03-13 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0004_ofertas_canceled'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertas',
            name='closed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
