# Generated by Django 3.1.2 on 2020-10-29 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeLancers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('sobrenome', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=16)),
                ('nascimento', models.DateField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='')),
                ('rg', models.CharField(blank=True, max_length=16, null=True, unique=True)),
                ('foto_doc', models.ImageField(blank=True, null=True, upload_to='')),
                ('bio', models.TextField()),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('owner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='freelancer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'freelancer',
                'verbose_name_plural': 'freelancers',
                'ordering': ['create'],
            },
        ),
    ]
