# Generated by Django 3.1.2 on 2020-11-10 22:33

from django.db import migrations, models
import freelancers.models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancers', '0002_auto_20201109_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancers',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=freelancers.models.upload_path),
        ),
    ]
