# Generated by Django 3.2.4 on 2021-06-15 14:43

from django.db import migrations, models
import django.db.models.deletion
import freelancers.models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancers', '0004_alter_freelancers_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelancers',
            name='foto_doc',
        ),
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frente', models.ImageField(upload_to=freelancers.models.upload_path)),
                ('verso', models.ImageField(upload_to=freelancers.models.upload_path)),
                ('selfie', models.ImageField(upload_to=freelancers.models.upload_path)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('freelancer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='freelancers.freelancers')),
            ],
        ),
    ]
