# Generated by Django 3.2.3 on 2021-06-17 00:02

from django.db import migrations, models
import freelancers.models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancers', '0006_auto_20210616_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentos',
            name='frente',
            field=models.ImageField(blank=True, null=True, upload_to=freelancers.models.upload_path_docs),
        ),
        migrations.AlterField(
            model_name='documentos',
            name='selfie',
            field=models.ImageField(blank=True, null=True, upload_to=freelancers.models.upload_path_docs),
        ),
        migrations.AlterField(
            model_name='documentos',
            name='verso',
            field=models.ImageField(blank=True, null=True, upload_to=freelancers.models.upload_path_docs),
        ),
    ]
