# Generated by Django 3.2.4 on 2021-06-18 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancers', '0007_auto_20210616_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancers',
            name='verificado',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
