# Generated by Django 3.1.2 on 2020-10-29 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ofertas', '0002_auto_20201029_1808'),
    ]

    operations = [
        migrations.CreateModel(
            name='Confirmados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ofertas.ofertas')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='confirmados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'confirmado',
                'verbose_name_plural': 'confirmados',
                'ordering': ['-create'],
            },
        ),
    ]
