# Generated by Django 3.1.2 on 2020-10-29 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estabelecimentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cpf_cnpj', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('razao_social', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=16)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('owner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estabelecimento', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'estabelecimento',
                'verbose_name_plural': 'estabelecimentos',
                'ordering': ['nome'],
            },
        ),
    ]
