# Generated by Django 3.1.2 on 2020-11-10 22:33

from django.db import migrations, models
import estabelecimentos.models


class Migration(migrations.Migration):

    dependencies = [
        ('estabelecimentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estabelecimentos',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=estabelecimentos.models.upload_path),
        ),
    ]
