# Generated by Django 3.2 on 2021-05-15 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planos', '0001_initial'),
        ('estabelecimentos', '0003_alter_estabelecimentos_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='estabelecimentos',
            name='ofertas_para_publicar',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='estabelecimentos',
            name='plano_contratado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planos.planos'),
        ),
    ]
