# Generated by Django 3.2 on 2021-05-26 01:12

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('estabelecimentos', '0004_auto_20210515_1604'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='estabelecimentos',
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
