# Generated by Django 3.2.3 on 2021-06-01 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estabelecimentos', '0005_alter_estabelecimentos_managers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estabelecimentos',
            old_name='cpf_cnpj',
            new_name='cnpj',
        ),
    ]
