# Generated by Django 3.2.5 on 2021-09-13 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportes',
            options={'ordering': ['-created'], 'verbose_name': 'reporte', 'verbose_name_plural': 'reportes'},
        ),
    ]
