# Generated by Django 3.2.5 on 2021-07-06 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0003_tokenproxy'),
        ('avaliacoes', '0002_alter_avaliacoes_id'),
        ('cancelados', '0003_alter_cancelados_id'),
        ('enderecos', '0003_enderecos_cep'),
        ('confirmados', '0002_alter_confirmados_id'),
        ('freelancers', '0008_freelancers_verificado'),
        ('estabelecimentos', '0006_rename_cpf_cnpj_estabelecimentos_cnpj'),
        ('ofertas', '0006_auto_20210511_2058'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('interesses', '0002_alter_interesses_id'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
