# Generated by Django 3.2 on 2021-05-26 01:12

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('planos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='planos',
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
